create extension if not exists pgcrypto;
create table if not exists profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,phone text,role text default 'customer' check(role in ('customer','admin')),created_at timestamptz default now());
create table if not exists products(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,description text,price numeric not null default 0,compare_at_price numeric,category text not null,subcategory text,brand text,images jsonb default '[]'::jsonb,colors jsonb default '[]'::jsonb,sizes jsonb default '[]'::jsonb,stock integer default 0,rating numeric default 0,review_count integer default 0,featured boolean default false,trending boolean default false,new_arrival boolean default false,created_at timestamptz default now());
create table if not exists orders(id uuid primary key default gen_random_uuid(),order_number text unique not null,customer_id uuid references auth.users(id) on delete set null,customer_name text not null,phone text not null,email text,address jsonb not null,products jsonb not null,subtotal numeric not null,delivery_charge numeric not null,total numeric not null,payment_method text default 'cod',payment_status text default 'pending',order_status text default 'Pending',created_at timestamptz default now());
create table if not exists order_items(id uuid primary key default gen_random_uuid(),order_id uuid references orders(id) on delete cascade,product_id uuid references products(id) on delete set null,quantity integer not null,price numeric not null,size text,color text);
create table if not exists categories(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,image text);
create table if not exists wishlists(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,created_at timestamptz default now(),unique(user_id));
create table if not exists wishlist_items(id uuid primary key default gen_random_uuid(),wishlist_id uuid references wishlists(id) on delete cascade,product_id uuid references products(id) on delete cascade,unique(wishlist_id,product_id));
create table if not exists reviews(id uuid primary key default gen_random_uuid(),product_id uuid references products(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,rating integer check(rating between 1 and 5),comment text,created_at timestamptz default now());

alter table profiles enable row level security; alter table products enable row level security; alter table orders enable row level security; alter table wishlists enable row level security; alter table wishlist_items enable row level security; alter table reviews enable row level security;
drop policy if exists "Public can read products" on products; create policy "Public can read products" on products for select using(true);
drop policy if exists "Users can read own orders" on orders; create policy "Users can read own orders" on orders for select using(auth.uid()=customer_id);
drop policy if exists "Users can create own orders" on orders; create policy "Users can create own orders" on orders for insert with check(auth.uid()=customer_id or customer_id is null);
drop policy if exists "Users can read own profile" on profiles; create policy "Users can read own profile" on profiles for select using(auth.uid()=id);
create policy "Public can read reviews" on reviews for select using(true);
-- Production-এ admin role অনুযায়ী products/orders write policies আলাদাভাবে যোগ করুন। Service role key কখনো browser-এ রাখবেন না।
